packages:
  - packages/*
  - examples/*

catalog:
  '@types/node': ^25.6.2
  '@types/js-yaml': ^4.0.9
  typescript: ^6
  vitest: ^4.1.7
  tsup: ^8.5.1
  zod: ^4.4.3
  js-yaml: ^4.1.0

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - sharp
