// GENERATED by stackwright-prebuild — do not edit.
// To regenerate: pnpm predev (or pnpm prebuild)
//
// This file is safe to commit. It will be updated whenever your YAML content changes.

import { Bot, Box, Camera, CircleAlert, CircleCheck, Code, Code2, FileCode, FilePlus, FileText, FlaskConical, Globe, Hammer, Image, Info, Layers, Layout, Map, Moon, Package, Palette, Plug, Rocket, Search, Shield, ShieldCheck, Smartphone, Sparkles, Sun, Terminal, TriangleAlert, Zap } from 'lucide-react';
import {
  BlueSkyIcon,
  StackwrightIcon,
  registerStackwrightIcons,
} from '@stackwright/icons';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const siteIconPreset: Record<string, React.ComponentType<any>> = {
  Bot,
  Box,
  Camera,
  CircleAlert,
  'CheckCircle': CircleCheck, // legacy MUI alias — candidate for deprecation
  Code,
  Code2,
  FileCode,
  FilePlus,
  FileText,
  FlaskConical,
  Globe,
  Hammer,
  Image,
  Info,
  Layers,
  Layout,
  Map,
  Moon,
  Package,
  Palette,
  Plug,
  Rocket,
  Search,
  Shield,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Sun,
  Terminal,
  TriangleAlert,
  Zap,
  // Brand icons — always included
  bluesky: BlueSkyIcon,
  stackwright: StackwrightIcon,
};

export function registerSiteIcons(): void {
  registerStackwrightIcons(siteIconPreset);
}
