'use client';
import { registerAppRouterComponents } from '@stackwright/nextjs/app-router';
import { registerShadcnComponents } from '@stackwright/ui-shadcn';
import '@stackwright/ui-shadcn/styles.css';
import { registerCollectionProvider } from '@stackwright/core';
import { FileCollectionProvider } from '@stackwright/collections';
// Generated by stackwright-prebuild. Run `pnpm predev` to regenerate when icons change.
// This file is safe to commit — it is updated deterministically from your YAML content.
import { registerSiteIcons } from '../../stackwright-generated/icons';

registerAppRouterComponents();
registerSiteIcons();
registerShadcnComponents();
registerCollectionProvider(new FileCollectionProvider());

export function Providers({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
