import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { getTypes } from '@stackwright/cli';
import type { ContentTypeEntry } from '@stackwright/cli';
import { z } from 'zod';
import fs from 'fs';
import path from 'path';

function formatContentType(ct: ContentTypeEntry): string {
  const lines: string[] = [`  ${ct.name} (${ct.typeName})`];
  for (const f of ct.fields) {
    lines.push(`    ${f.name}${f.required ? '' : '?'}: ${f.type}`);
  }
  return lines.join('\n');
}

export function registerContentTypeTools(server: McpServer): void {
  server.tool(
    'stackwright_get_content_types',
    'List all available Stackwright content types with their fields. Call this before writing any YAML content to know what keys and types are valid.',
    {},
    async () => {
      const result = getTypes();

      const contentSection = [
        'CONTENT TYPES (use as keys inside content_items[]):',
        ...result.contentTypes.map(formatContentType),
      ].join('\n');

      const subSection = [
        'SUB-TYPES (used as field values within content types):',
        ...result.subTypes.map(formatContentType),
      ].join('\n');

      return {
        content: [
          {
            type: 'text',
            text:
              [contentSection, subSection].join('\n\n') +
              '\n\nTip: Call stackwright_preview_component with a content type name to see a visual preview screenshot.',
          },
        ],
      };
    }
  );

  // Resolve the screenshots directory relative to the package root.
  // Walk up from __dirname until we find package.json to locate the MCP package root.
  function findPackageRoot(dir: string): string {
    if (fs.existsSync(path.join(dir, 'package.json'))) return dir;
    const parent = path.dirname(dir);
    if (parent === dir) return dir; // filesystem root
    return findPackageRoot(parent);
  }
  const screenshotsDir = path.join(findPackageRoot(__dirname), 'screenshots');

  const KNOWN_CONTENT_TYPES = [
    'main',
    'carousel',
    'timeline',
    'icon_grid',
    'tabbed_content',
    'code_block',
    'feature_list',
    'testimonial_grid',
    'faq',
    'pricing_table',
    'alert',
    'contact_form_stub',
  ];

  server.tool(
    'stackwright_preview_component',
    'Show a visual preview screenshot of a Stackwright content type. Returns a PNG image of how the component renders with example data.',
    {
      content_type: z
        .string()
        .describe(`The content type to preview. One of: ${KNOWN_CONTENT_TYPES.join(', ')}`),
    },
    async ({ content_type }) => {
      if (!KNOWN_CONTENT_TYPES.includes(content_type)) {
        return {
          content: [
            {
              type: 'text' as const,
              text: `Unknown content type "${content_type}". Valid types: ${KNOWN_CONTENT_TYPES.join(', ')}`,
            },
          ],
          isError: true,
        };
      }

      // Screenshot filenames use hyphens (Playwright sanitizes underscores)
      const fileName = content_type.replace(/_/g, '-');
      const screenshotPath = path.join(screenshotsDir, `${fileName}-desktop.png`);

      if (!fs.existsSync(screenshotPath)) {
        return {
          content: [
            {
              type: 'text' as const,
              text: `No preview screenshot available for "${content_type}". Screenshots are generated by running E2E tests with --update-snapshots.`,
            },
          ],
        };
      }

      const imageData = fs.readFileSync(screenshotPath, 'base64');

      return {
        content: [
          {
            type: 'text' as const,
            text: `Preview of the "${content_type}" content type (desktop viewport, 1280px wide):`,
          },
          {
            type: 'image' as const,
            data: imageData,
            mimeType: 'image/png',
          },
        ],
      };
    }
  );
}
